import type { Metadata } from "next";
import { Award, BriefcaseBusiness, Users } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { AppointmentCta } from "@/components/sections/cta";
import Link from "next/link";

export const metadata: Metadata = { title: "Accredited Beauty Courses Reading", description: "Professional, accredited beauty training and courses at Pink Beauty Academy in Reading." };
const courses = [
  { title: "VTCT Level 2 NVQ Diploma in Beauty Therapy General", price: "£2,399", duration: "Approx. 14 weeks · one day per week", entry: "Beginner-friendly · age 16+" },
  { title: "VTCT Level 3 NVQ Diploma in Beauty Therapy General", price: "£2,499", duration: "Approx. 15–16 weeks · one day per week", entry: "Recognised Level 2 Beauty Therapy required" },
  { title: "VTCT Skills Level 2 Award in Facial Massage and Skin Care", price: "£950", duration: "Approx. 4–5 weeks", entry: "No prior beauty qualification required · age 16+" },
  { title: "VTCT Skills Level 3 Award in Anatomical and Physiological Knowledge of Body Systems", price: "£350", duration: "Flexible guided learning and home study", entry: "No prior anatomy qualification required · age 16+" },
  { title: "VTCT Skills Level 4 Certificate in Laser and IPL Treatments", price: "£1,499", duration: "Approx. 6 weeks · one day per week", entry: "Recognised Level 3 Beauty Therapy required" },
  { title: "VTCT Level 4 Certificate in Micropigmentation", price: "£2,599", duration: "Schedule confirmed on enrolment", entry: "Entry requirements confirmed by the academy" },
];

export default function CoursesPage() {
  return <main><PageHero eyebrow="Pink Beauty Academy" title="Turn passion into profession." copy="Accredited, practical beauty training from experienced educators who understand what it takes to build a successful career." image="https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=2200&q=90" /><section className="section-shell bg-white"><div className="container-site"><div className="grid gap-3 md:grid-cols-3 sm:gap-4">{[[Award,"Ofqual-regulated learning"],[Users,"Practical assessment"],[BriefcaseBusiness,"Industry-recognised skills"]].map(([Icon,title]) => { const I = Icon as typeof Award; return <article key={title as string} className="flex items-center gap-4 rounded-2xl bg-pink-light/50 p-4 sm:block sm:rounded-[1.5rem] sm:p-7"><I className="shrink-0 text-pink" /><h2 className="font-display text-2xl sm:mt-7 sm:text-3xl">{title as string}</h2></article>})}</div><div className="mt-12 grid gap-8 sm:mt-20 sm:gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">Study with Pink</p><h2 className="section-title">Courses built for your future.</h2><p className="mt-4 text-sm leading-6 text-black/50 sm:mt-6 sm:leading-7">VTCT Skills qualifications combine theory, supervised practical work, assessment and portfolio evidence. Published course dates change through the year, so current availability is confirmed before enrolment.</p><div className="mt-5 rounded-2xl bg-pink-light/50 p-4 text-xs leading-6 text-black/55">Course prices shown are the published West Street prices. Watlington Street offers and prices may differ. Confirm dates, assessments, kit requirements and payment terms with the academy.</div></div><div className="grid gap-3 sm:grid-cols-2">{courses.map((course,i) => <Link href={`/contact?type=course&course=${encodeURIComponent(course.title)}`} key={course.title} className="group flex min-h-52 flex-col items-start rounded-2xl border border-black/5 bg-cream p-5 transition hover:-translate-y-1 hover:shadow-soft sm:rounded-[1.5rem] sm:p-6"><div className="flex w-full items-center justify-between gap-3"><span className="text-[10px] font-bold text-pink sm:text-xs">0{i+1}</span><span className="text-sm font-bold text-pink">{course.price}</span></div><h3 className="mt-4 font-display text-2xl leading-none">{course.title}</h3><div className="mt-4 grid gap-2 text-[11px] leading-5 text-black/50"><p>{course.duration}</p><p>{course.entry}</p></div><span className="mt-auto pt-4 text-[10px] font-bold uppercase tracking-[.12em] text-pink">Request dates & enrolment details</span></Link>)}</div></div></div></section><AppointmentCta /></main>;
}
