import { PolicyPage } from "@/components/policy-page";

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Your information" title="Privacy." intro="This notice explains how information submitted through Pink Beauty’s website is used across the two Reading businesses." sections={[
    { title: "Data controllers and contact", body: "For West Street, the controller is Pink Beauty Salon Ltd T/A Pink Beauty Salon and Academy (company number 10812181), 4–5 West Street, Reading RG1 1TT, info@pinkbeautysalons.co.uk, 0118 996 2711. For Watlington Street, the controller is VB Wholesale UK Ltd T/A Pink, 25 Watlington Street, Reading RG1 4EN, pinkbeautyreading@gmail.com, 0118 402 8505." },
    { title: "Information collected", body: "Depending on how you use the site, we may collect your name, contact and address details, selected branch, order and appointment details, payment confirmation, support messages, consent choices, device and browser information, IP address and site usage. Health information is collected only through the appropriate consultation or treatment process." },
    { title: "Purposes and lawful use", body: "Information is used to answer enquiries, take steps at your request, perform orders and bookings, arrange delivery, provide treatment and aftercare, keep clinical or business records, prevent fraud, improve the service, send marketing where permitted and meet legal obligations. We retain information only for as long as required for those purposes and applicable professional, tax or legal record-keeping." },
    { title: "Payment providers, including Klarna", body: "Payment and fraud-prevention information may be sent to the payment provider offered for your selected branch. If you choose Klarna, information needed to assess and administer that payment may be shared with Klarna, which processes it under its own privacy notice. Pink Beauty does not receive or store full card details entered in a provider-hosted payment form." },
    { title: "Other processors and international transfers", body: "Relevant information may be handled by providers supporting hosting, content management, payments, communications, delivery, analytics, booking and customer support. Providers are expected to protect it and use it only for agreed purposes. Where information is transferred outside the UK, appropriate safeguards are required." },
    { title: "Your rights", body: "Depending on the circumstances, you may ask for access, correction, deletion, restriction, portability or objection, and may withdraw consent where consent is relied upon. Contact the relevant branch first. You may also complain to the UK Information Commissioner’s Office." },
  ]} />;
}
