import { PolicyPage } from "@/components/policy-page";

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Your information" title="Privacy." intro="This notice explains how Pink Beauty Salon & Academy and Pink Beauty Clinic collect and use personal information through this website and when providing products, treatments and courses." sections={[
    { title: "Who is responsible for your information", body: "For Pink Beauty Salon & Academy at West Street, the data controller is Pink Beauty Salon Ltd, trading as Pink Beauty Salon & Academy (company number 10812181), 4–5 West Street, Reading RG1 1TT, info@pinkbeautysalons.co.uk, 0118 996 2711. For Pink Beauty Clinic at Watlington Street, the data controller is VB Wholesale UK Ltd, trading as Pink Beauty Clinic, 25 Watlington Street, Reading RG1 4EN, pinkbeautyreading@gmail.com, 0118 402 8505. The business responsible for your booking, purchase, course or enquiry is the controller for that activity." },
    { title: "Information collected", body: "Depending on how you use the site, we may collect your name, contact and address details, selected branch, order and appointment details, payment confirmation, support messages, consent choices, device and browser information, IP address and site usage. Health information is collected only through the appropriate consultation or treatment process." },
    { title: "How and why we use it", body: "We use information to answer enquiries, manage accounts, take payment, fulfil orders, arrange delivery, administer appointments and course enrolments, assess treatment suitability, provide treatment and aftercare, keep clinical and training records, prevent fraud, improve our services, send marketing where permitted and comply with legal obligations. Our lawful bases may include performing a contract, taking steps before a contract, consent, legitimate interests and compliance with law. Health information is handled only where an additional lawful condition applies, such as your explicit consent or the provision of health or care services." },
    { title: "Payment providers, including Klarna", body: "Payment and fraud-prevention information may be sent to the payment provider offered for your selected branch. If you choose Klarna, information needed to assess and administer that payment may be shared with Klarna, which processes it under its own privacy notice. Pink Beauty does not receive or store full card details entered in a provider-hosted payment form." },
    { title: "Sharing, transfers and retention", body: "Relevant information may be handled by providers supporting website hosting, content management, payments, communications, delivery, analytics, bookings and customer support, or disclosed where required by law. Providers must protect it and use it only for agreed purposes. Where information is transferred outside the UK, appropriate safeguards are required. We retain information only for as long as needed for these purposes and for applicable clinical, professional, safeguarding, insurance, tax and legal record-keeping periods." },
    { title: "Marketing and your choices", body: "We send marketing by email or text only where we are permitted to do so. You can unsubscribe using the link in a message or contact the relevant business at any time. Service messages about an order, appointment, treatment or course are not marketing and may still be sent where necessary." },
    { title: "Your rights", body: "Depending on the circumstances, you may ask for access, correction, deletion, restriction or portability of your information, object to certain use, or withdraw consent where consent is relied upon. Contact the business responsible for your interaction using the details above. You may also complain to the UK Information Commissioner’s Office at ico.org.uk." },
  ]} />;
}
