"use client";

import Link from "next/link";
import { ArrowLeft, Check, CreditCard, Lock, MapPin, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useBasket } from "@/components/providers/basket-provider";
import type { Branch } from "@/lib/branches";
import type { BranchPaymentConfig } from "@/lib/payments/providers";

export function BasketCheckout({ branch, payment }: { branch: Branch; payment: BranchPaymentConfig }) {
  const { items, total } = useBasket();
  const [showProvider, setShowProvider] = useState(false);
  const branchItems = items.filter((item) => item.branchId === branch.id);

  if (!branchItems.length) return <main className="min-h-screen bg-cream pt-28"><div className="container-site py-20 text-center"><h1 className="font-display text-5xl">Your basket is empty.</h1><Link href="/basket" className="button-primary mt-6">Return to basket</Link></div></main>;

  if (showProvider) return <main className="min-h-screen bg-pink-light/30 pt-24"><section className="mx-auto max-w-xl px-5 py-16"><div className="overflow-hidden rounded-[2rem] bg-white shadow-soft"><div className={`h-2 ${payment.provider === "lopay" ? "bg-[#6657ff]" : "bg-[#00a98f]"}`} /><div className="p-7 text-center sm:p-10"><Lock className="mx-auto text-pink" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.25em] text-black/40">Provider preview</p><h1 className="mt-2 font-display text-5xl">{payment.providerName}</h1><p className="mt-2 text-sm font-bold">{payment.businessName}</p><div className="mt-7 rounded-2xl bg-cream p-5 text-left">{branchItems.map((item) => <div key={item.id} className="flex justify-between gap-4 border-b border-black/5 py-2 text-xs"><span>{item.quantity} × {item.title} · {item.variantName}</span><span className="font-bold">£{(item.unitPrice * item.quantity).toFixed(2)}</span></div>)}<div className="mt-3 flex justify-between text-lg font-bold"><span>Total</span><span>£{total.toFixed(2)}</span></div></div><div className="mt-5 rounded-2xl border border-dashed border-black/15 p-6 text-sm text-black/45">The live {payment.providerName} payment form will appear here. This mock-up does not collect card details.</div><button disabled className="mt-6 min-h-12 w-full rounded-full bg-black/15 text-sm font-bold text-white">Pay £{total.toFixed(2)} · Demo only</button><button type="button" onClick={() => setShowProvider(false)} className="mt-5 text-xs font-bold text-pink underline">Return to checkout</button></div></div></section></main>;

  return <main className="min-h-screen bg-pink-light/30 pt-20 sm:pt-24"><section className="container-site grid gap-8 py-10 sm:py-16 lg:grid-cols-[1fr_420px] lg:gap-12"><div><Link href="/basket" className="inline-flex items-center gap-2 text-xs font-bold text-pink"><ArrowLeft size={15} /> Back to basket</Link><p className="mt-9 text-[10px] font-bold uppercase tracking-[.3em] text-pink">Pink Beauty secure checkout</p><h1 className="mt-3 font-display text-5xl sm:text-7xl">Complete your payment.</h1><div className="mt-8 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold">First name<input className="rounded-xl border border-black/10 bg-white px-4 py-3.5 outline-none focus:border-pink" /></label><label className="grid gap-2 text-xs font-bold">Last name<input className="rounded-xl border border-black/10 bg-white px-4 py-3.5 outline-none focus:border-pink" /></label><label className="grid gap-2 text-xs font-bold sm:col-span-2">Email address<input type="email" className="rounded-xl border border-black/10 bg-white px-4 py-3.5 outline-none focus:border-pink" /></label></div><div className="mt-6 flex gap-3 rounded-2xl bg-white p-4 text-xs leading-5 text-black/50"><ShieldCheck className="shrink-0 text-pink" size={18} />Card details will be handled by {payment.providerName}, not stored by Pink Beauty.</div></div><aside className="h-fit rounded-[2rem] bg-[#210013] p-6 text-white shadow-soft sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-pink-light">Order summary</p><div className="mt-5 flex gap-3 border-b border-white/10 pb-5"><MapPin className="shrink-0 text-pink-light" size={17} /><div><p className="text-sm font-bold">{branch.name}</p><p className="mt-1 text-xs text-white/45">{branch.address}</p></div></div><div className="divide-y divide-white/10">{branchItems.map((item) => <div key={item.id} className="flex justify-between gap-4 py-4 text-xs"><div><p className="font-bold">{item.quantity} × {item.title}</p><p className="mt-1 text-white/40">{item.variantName}</p></div><span>£{(item.unitPrice * item.quantity).toFixed(2)}</span></div>)}</div><div className="flex justify-between border-t border-white/10 py-6"><span className="text-white/55">Total</span><span className="text-3xl font-bold">£{total.toFixed(2)}</span></div><button type="button" onClick={() => setShowProvider(true)} className="button-primary w-full"><CreditCard size={16} /> Continue with {payment.providerName}</button><p className="mt-4 flex items-center justify-center gap-2 text-[10px] text-white/40"><Check size={12} /> {payment.checkoutDescription}</p></aside></section></main>;
}
