import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";

export const metadata: Metadata = { title: "Terms and Conditions", description: "Terms for Pink Beauty treatments, courses and product purchases.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <PolicyPage eyebrow="Purchases and bookings" title="Terms." intro="These terms explain the key conditions that apply when you buy products, book services or enrol on a course with either Pink Beauty business." sections={[
    { title: "Who you are buying from", body: "Your contract is with the business operating the branch shown at booking or checkout. West Street is Pink Beauty Salon Ltd, trading as Pink Beauty Salon & Academy (company number 10812181), whose registered office and trading address is 4–5 West Street, Reading RG1 1TT. Watlington Street is VB Wholesale (UK) Ltd, trading as Pink Beauty Clinic (company number 11470499), whose registered office is Unit 9 Kelvin Industrial Estate, Greenford UB6 8GB and whose trading address is 25 Watlington Street, Reading RG1 4EN. Both companies are registered in England and Wales. Together they are referred to on this website as Pink Beauty, but each business is responsible for its own bookings, courses and sales." },
    { title: "Prices, orders and payment", body: "All totals are shown in pounds sterling. The selected branch, item, option and current total are shown before payment. An order or booking is accepted when the relevant branch confirms it. We may decline or cancel an order where an item, appointment or price is unavailable or clearly incorrect, and will return any payment due using the original payment method." },
    { title: "Treatments and services", body: "Treatment suitability remains subject to consultation, health screening, informed consent and any required patch test. We may refuse, postpone or recommend an alternative treatment where it would be unsafe or unsuitable. Results vary between individuals and cannot be guaranteed. Appointments, deposits, prepaid treatments and packages are subject to the Cancellations and Returns policies and any specific conditions shown before payment." },
    { title: "Courses and academy enrolment", body: "Check the course description, dates, entry requirements, accreditation, model requirements and kit arrangements before enrolling. A course place is reserved once enrolment and any required payment are accepted. Course fees and deposits are non-refundable and non-transferable after enrolment, except where Pink Beauty Salon & Academy cancels the course or where a refund is required by law. If you enrol online or by phone, any statutory cancellation period and any request to begin the course during that period are dealt with in the Cancellations policy." },
    { title: "Prepaid sessions, packages and gift cards", body: "Prepaid treatments and packages are for the named customer, branch, treatment and treatment area unless agreed otherwise. They cannot normally be exchanged, shared or transferred and must be used within the validity period stated when purchased; where no different period is stated, the normal validity is 12 months. Gift cards and vouchers are subject to the expiry date and conditions supplied with them." },
    { title: "Third-party payment services", body: "The payment options displayed at checkout are provided by the payment provider selected for the relevant branch. If PayPal Pay Later is displayed for an eligible purchase, the credit agreement is between the customer and PayPal, is subject to status and PayPal's terms, and may not be available for every purchase. Pink Beauty does not make the credit decision. Choosing a payment provider does not change your statutory rights or the selling Pink Beauty business's responsibility for the order." },
    { title: "Changes and statutory rights", body: "Prices, offers and availability may change before an order is accepted. Nothing in these terms limits rights that cannot lawfully be excluded, including rights relating to goods or services that are faulty, not as described or not provided with reasonable care and skill." },
  ]} />;
}
