import { PolicyPage } from "@/components/policy-page";

export default function CancellationsPage() {
  return <PolicyPage eyebrow="Appointments and courses" title="Cancellations." intro="These arrangements cover appointment changes, cancelled services and academy course enrolments. Contact the relevant Pink Beauty business as soon as your plans change." sections={[
    { title: "Pink Beauty Salon & Academy appointments", body: "West Street requires at least 48 hours’ notice to cancel or change an appointment. If less notice is given, or you do not attend, the deposit may be retained, a cancellation fee may apply, or the session may be deducted from a prepaid package. Any branch-specific condition shown when booking also applies." },
    { title: "Pink Beauty Clinic appointments", body: "Watlington Street requires at least 24 hours’ notice to cancel or reschedule an appointment. If less notice is given, or you do not attend, the deposit or service payment may be retained, a cancellation fee may apply, or the session may be deducted from a prepaid package. Any branch-specific condition shown when booking also applies." },
    { title: "Services booked at a distance", body: "Where the law gives you a 14-day cancellation right for a service booked online or by phone, you may cancel during that period unless an exception applies. If you ask us to begin the service during the cancellation period, you must pay for the part supplied before cancellation. Once the service has been fully performed after your express request and acknowledgement, the cancellation right is lost. This does not affect rights where a service is faulty, misdescribed or not provided with reasonable care and skill." },
    { title: "Courses and enrolment fees", body: "Course places, course fees and deposits are non-refundable and non-transferable once you are enrolled, except where Pink Beauty Salon & Academy cancels the course or the law requires otherwise. For an online or telephone enrolment, any statutory cancellation right applies unless the course has begun at your express request; if it has begun, a proportionate charge may be due, and the right is lost once the course has been fully provided after the required acknowledgement. Failure to attend does not create a right to a refund or transfer." },
    { title: "Changes made by Pink Beauty", body: "If we need to cancel an appointment or course, we will offer a suitable replacement date, credit or refund for the part we cannot provide. We are not responsible for unrelated costs you incur, except where the law says otherwise." },
    { title: "How to make a change", body: "Call Pink Beauty Salon & Academy on 0118 996 2711 or Pink Beauty Clinic on 0118 402 8505 and provide your name and appointment, course or order details. The relevant business will confirm any rescheduling, credit or refund that applies." },
  ]} />;
}
