import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";

export const metadata: Metadata = { title: "Returns Policy", description: "Returns and refunds information for Pink Beauty product purchases.", alternates: { canonical: "/returns" } };

export default function ReturnsPage() {
  return <PolicyPage eyebrow="Products, services and courses" title="Returns & refunds." intro="Different refund rules apply to physical products, beauty and aesthetic services, prepaid treatments, and academy courses." sections={[
    { title: "Physical product returns", body: "For an eligible product bought online or by phone, tell the selling business within 14 days after receiving it that you wish to cancel, then return it within the following 14 days. The item must be unused and handled only as necessary to inspect it, with any tags and original packaging where reasonably possible, and accompanied by proof of purchase. Contact Pink Beauty Salon & Academy at info@pinkbeautysalons.co.uk or Pink Beauty Clinic at pinkbeautyreading@gmail.com before sending anything." },
    { title: "Return addresses", body: "Accepted West Street returns are sent to 4–5 West Street, Reading RG1 1TT. Accepted Watlington Street returns are sent to 25 Watlington Street, Reading RG1 4EN. The branch will provide return instructions and confirm who is responsible for return postage." },
    { title: "Product exceptions", body: "Sealed personal-care, cosmetic and beauty products cannot normally be returned after they have been unsealed where they are not suitable for return for health-protection or hygiene reasons. Custom or personalised items and perishable goods may also be excluded. Sale items have the same statutory rights as full-price items. These exceptions do not remove your rights where goods are faulty, damaged or not as described." },
    { title: "Damaged, incorrect or faulty items", body: "Inspect the order when it arrives and contact the relevant branch promptly if it is damaged, defective or incorrect. Include the order details and photographs where useful. Your statutory rights for faulty or misdescribed goods are not affected." },
    { title: "Services, appointments and prepaid treatments", body: "Treatments and other services cannot be returned like physical goods. Completed or partly completed services are normally non-refundable, except where required by law, including where a service was not provided with reasonable care and skill or was not as agreed. Deposits, missed appointments and late cancellations are handled under the Cancellations policy. Unused prepaid sessions or packages are normally non-refundable and non-transferable, subject to any statutory cancellation right." },
    { title: "Academy courses", body: "Course places, fees and deposits are non-refundable and non-transferable once enrolment is accepted. No refund or transfer is given because a student changes their mind, cannot attend or does not complete the course. This does not affect any statutory cancellation right that still applies, or your right to an appropriate remedy if Pink Beauty Salon & Academy cancels or fails to provide the course with reasonable care and skill." },
    { title: "Refund timing", body: "For an approved product return, the relevant business will refund the price and any basic outbound delivery charge required by law to the original payment method, normally within 14 days of receiving the returned item or evidence that it was sent. For an approved service or course refund, we will confirm the amount and timing in writing. Your bank or payment provider may need additional processing time." },
  ]} />;
}
