"use client";

import type { LaserAreaSetting } from "@/lib/admin/laser-settings";

const areas = ["Face", "Upper lip", "Chin", "Jawline", "Neck", "Underarms", "Arms", "Hands / fingers", "Chest", "Abdomen", "Back", "Bikini line", "Brazilian", "Hollywood", "Buttocks", "Legs", "Feet / toes", "Other"];
const cls = "w-full rounded-xl border border-black/10 bg-cream px-4 py-3 text-sm outline-none focus:border-pink";
const blank = (): LaserAreaSetting => ({ area: "", fluence: "", hertz: "", shotsFired: "", pulse: "Auto by machine" });

export function LaserAreaSettings({ value, onChange }: { value: LaserAreaSetting[]; onChange: (value: LaserAreaSetting[]) => void }) {
  const rows = value.length ? value : [blank()];
  function update(index: number, field: keyof LaserAreaSetting, nextValue: string) {
    onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: nextValue } : row));
  }
  return <section className="grid gap-4 rounded-xl bg-pink-light/35 p-4 sm:col-span-2"><div><p className="text-xs font-bold">Laser settings by treatment area <span className="text-pink">*</span></p><p className="mt-1 text-xs text-black/50">Record a separate set of machine settings for every area treated in this visit.</p></div>{rows.map((row, index) => <div key={index} className="grid gap-3 rounded-xl border border-black/10 bg-white p-3 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold">Body area<select required value={row.area} onChange={(event) => update(index, "area", event.target.value)} className={cls}><option value="" disabled>Select area</option>{areas.map((area) => <option key={area} value={area}>{area}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Fluence<select required value={row.fluence} onChange={(event) => update(index, "fluence", event.target.value)} className={cls}><option value="" disabled>Select fluence</option>{Array.from({ length: 80 }, (_, itemIndex) => itemIndex + 1).map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Hertz<select required value={row.hertz} onChange={(event) => update(index, "hertz", event.target.value)} className={cls}><option value="" disabled>Select hertz</option>{Array.from({ length: 10 }, (_, itemIndex) => itemIndex + 1).map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Shots fired<input required type="number" min="0" step="1" inputMode="numeric" value={row.shotsFired} onChange={(event) => update(index, "shotsFired", event.target.value)} className={cls} /></label><label className="grid gap-2 text-xs font-bold">Pulse<select required value={row.pulse} onChange={(event) => update(index, "pulse", event.target.value)} className={cls}><option value="Auto by machine">Auto by machine</option></select></label><div className="flex flex-wrap items-end gap-2"><button type="button" onClick={() => onChange([...rows, { ...row, area: "" }])} className="rounded-xl border border-pink px-3 py-2 text-xs font-bold text-pink">Duplicate settings</button>{rows.length > 1 && <button type="button" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Remove area</button>}</div></div>)}<button type="button" onClick={() => onChange([...rows, blank()])} className="justify-self-start rounded-full border border-pink px-4 py-2 text-xs font-bold text-pink">+ Add another body area</button></section>;
}
